services:
  mysql: #数据库
    image: mysql:8.0
    container_name: netchat-mysql   #设置容器名称
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   #root用户密码
      MYSQL_DATABASE: netchat   #启动时自动创建数据库
      MYSQL_USER: netchat   #自动创建普通用户
      MYSQL_PASSWORD: netchat   #设置普通用户密码
    ports:    #设置端口映射
      - "3306:3306"
    volumes:    #挂载数据卷
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - go-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s  # MySQL 启动较慢，需要更长时间

  redis: #redis
    image: redis:8.4.0
    container_name: netchat-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
    networks:
      - go-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s      # 每3秒检查一次
      timeout: 2s       # 每次检查最多等2秒
      retries: 10       # 连续失败10次才认为不健康
      start_period: 5s # 给Redis 5秒启动时间


  server:   #服务端
    build:
      context: .  #设置构建上下文
      dockerfile: Dockerfile-servers
    container_name: netchat-server
    depends_on:   #保证在mysql后面启动
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8888:8888"
    networks:
      - go-net



  clients:    #客户端
    build:
      context: .
      dockerfile: Dockerfile-clients
    container_name: netchat-client
    depends_on:
      - server
    networks:
      - go-net
    command: tail -f /dev/null  #覆盖掉CMD的./client



networks:
  go-net:

volumes:
  mysql-data:
  redis-data: